from modules import classes as cl

if __name__ == '__main__':
    print('Создадим по 1 экземпляру для каждого класса')
    student = cl.Student('Aleksandr', 'Stydentov', 'Male')
    lector = cl.Lecteur('Fedor Mikhailovich', 'Lectorov')
    reviwer = cl.Reviwer('Nikolay', 'Zloy')
    lst = (student, lector, reviwer)
    print('\nПроверим наших друзей\n')
    print(*lst, sep='\n\n')
    print('-' * 20)
    print('Добавили предметы и оценки')
    reviwer.courses_attached.extend(['Python', 'HTML', 'C#'])
    student.courses_in_progress.append('Python')
    student.courses_in_progress.append('C#')
    lector.courses_attached.extend(['Python', 'C#'])
    student.finished_courses.append('HTML')
    student.rate_lecteur(lector, 'Python', 2)
    student.rate_lecteur(lector, 'Python', 1)
    student.rate_lecteur(lector, 'C#', 9)
    reviwer.rate_hw(student, 'Python', 2)
    reviwer.rate_hw(student, 'Python', 7)
    reviwer.rate_hw(student, 'Python', 6)
    reviwer.rate_hw(student, 'HTML', 8) # нужен другой лектор ))
    print('\nПроверим наших друзей после получения оценок и предметов\n')
    print(*lst, sep='\n\n')
    print('-' * 20)
    print(student.__lt__(lector))
    print(lector < student)
    